version: "3.9"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: data_wizard_db
    ports:
      - "5432:5432"

  data_wizard_tool:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/data_wizard_db
      GCP_PROJECT: data-wizard-tool
      GOOGLE_APPLICATION_CREDENTIALS: /app/data-wizard-local.json
      JWT_SECRET_KEY: secret
    depends_on:
      - db
    volumes:
      - ./data-wizard-local.json:/app/data-wizard-local.json
      - .:/app  # Mount your application code

volumes:
  postgres_data:
